"""initial schema

Revision ID: 5ae8b26da9ad
Revises: 
Create Date: 2026-09-16 11:11:39.723379

"""
from alembic import op
import sqlalchemy as sa
from app.db import money as app_money  # noqa: F401
from app import types as app_types  # noqa: F401


revision = '5ae8b26da9ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allocation_policies',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('benefit_class', sa.String(length=64), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('share_pct', app_money.MoneyNumeric(), nullable=True),
    sa.Column('parameters', app_types.JSONVariant(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('org_path', sa.String(length=512), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_allocation_policies_org_id'), 'allocation_policies', ['org_id'], unique=False)
    op.create_index(op.f('ix_allocation_policies_org_path'), 'allocation_policies', ['org_path'], unique=False)
    op.create_table('audit_events',
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('actor_kind', sa.String(length=32), nullable=False),
    sa.Column('actor_label', sa.String(length=320), nullable=False),
    sa.Column('org_path', sa.String(length=512), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('detail', app_types.JSONVariant(), nullable=False),
    sa.Column('correlation_id', sa.String(length=32), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_actor_user_id'), 'audit_events', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_events_correlation_id'), 'audit_events', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_id'), 'audit_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_type'), 'audit_events', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_events_org_path'), 'audit_events', ['org_path'], unique=False)
    op.create_table('cloud_billing_accounts',
    sa.Column('provider_code', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('invoice_prefix', sa.String(length=64), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('extra', app_types.JSONVariant(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('org_path', sa.String(length=512), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cloud_billing_accounts_org_id'), 'cloud_billing_accounts', ['org_id'], unique=False)
    op.create_index(op.f('ix_cloud_billing_accounts_org_path'), 'cloud_billing_accounts', ['org_path'], unique=False)
    op.create_table('cloud_providers',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('adapter_key', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('customers',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('billing_email', sa.String(length=320), nullable=True),
    sa.Column('po_number', sa.String(length=128), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('target_margin_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('portal_enabled', sa.Boolean(), nullable=False),
    sa.Column('billing_contact_name', sa.String(length=255), nullable=True),
    sa.Column('billing_address', app_types.JSONVariant(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('org_path', sa.String(length=512), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_org_id'), 'customers', ['org_id'], unique=False)
    op.create_index(op.f('ix_customers_org_path'), 'customers', ['org_path'], unique=False)
    op.create_table('integrations',
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('config', app_types.JSONVariant(), nullable=False),
    sa.Column('secret_refs', app_types.JSONVariant(), nullable=False),
    sa.Column('last_check_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_check_ok', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('org_path', sa.String(length=512), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_path', 'kind', 'name', name='uq_integration_name')
    )
    op.create_index(op.f('ix_integrations_org_id'), 'integrations', ['org_id'], unique=False)
    op.create_index(op.f('ix_integrations_org_path'), 'integrations', ['org_path'], unique=False)
    op.create_table('invoice_sequences',
    sa.Column('org_path', sa.String(length=512), nullable=False),
    sa.Column('pattern_key', sa.String(length=64), nullable=False),
    sa.Column('next_value', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_path', 'pattern_key', name='uq_invoice_seq')
    )
    op.create_table('notification_outbox',
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('recipient', sa.String(length=320), nullable=False),
    sa.Column('subject', sa.String(length=512), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('org_path', sa.String(length=512), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_outbox_org_id'), 'notification_outbox', ['org_id'], unique=False)
    op.create_index(op.f('ix_notification_outbox_org_path'), 'notification_outbox', ['org_path'], unique=False)
    op.create_table('organizations',
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=True),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('billing_profile', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_id', 'name', name='uq_org_parent_name'),
    sa.UniqueConstraint('path')
    )
    op.create_index(op.f('ix_organizations_parent_id'), 'organizations', ['parent_id'], unique=False)
    op.create_table('permissions',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('provider_bill_totals',
    sa.Column('org_path', sa.String(length=512), nullable=False),
    sa.Column('provider_code', sa.String(length=32), nullable=False),
    sa.Column('billing_account_ref', sa.String(length=128), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('billed_total', app_money.MoneyNumeric(), nullable=False),
    sa.Column('credit_total', app_money.MoneyNumeric(), nullable=False),
    sa.Column('tax_total', app_money.MoneyNumeric(), nullable=False),
    sa.Column('support_total', app_money.MoneyNumeric(), nullable=False),
    sa.Column('marketplace_total', app_money.MoneyNumeric(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('evidence', app_types.JSONVariant(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_path', 'provider_code', 'billing_account_ref', 'period_start', name='uq_provider_bill')
    )
    op.create_table('roles',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.Column('is_customer_facing', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('webhook_endpoints',
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('events', app_types.JSONVariant(), nullable=False),
    sa.Column('secret_ref', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('org_path', sa.String(length=512), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_endpoints_org_id'), 'webhook_endpoints', ['org_id'], unique=False)
    op.create_index(op.f('ix_webhook_endpoints_org_path'), 'webhook_endpoints', ['org_path'], unique=False)
    op.create_table('account_families',
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('org_path', sa.String(length=512), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_path', 'name', name='uq_family_name_per_customer')
    )
    op.create_index(op.f('ix_account_families_customer_id'), 'account_families', ['customer_id'], unique=False)
    op.create_index(op.f('ix_account_families_org_id'), 'account_families', ['org_id'], unique=False)
    op.create_index(op.f('ix_account_families_org_path'), 'account_families', ['org_path'], unique=False)
    op.create_table('branding_configs',
    sa.Column('product_name', sa.String(length=128), nullable=False),
    sa.Column('logo_object_key', sa.String(length=512), nullable=True),
    sa.Column('favicon_object_key', sa.String(length=512), nullable=True),
    sa.Column('primary_color', sa.String(length=16), nullable=False),
    sa.Column('accent_color', sa.String(length=16), nullable=False),
    sa.Column('support_email', sa.String(length=320), nullable=True),
    sa.Column('email_sender_name', sa.String(length=128), nullable=True),
    sa.Column('custom_domain', sa.String(length=255), nullable=True),
    sa.Column('terminology', app_types.JSONVariant(), nullable=False),
    sa.Column('feature_flags', app_types.JSONVariant(), nullable=False),
    sa.Column('invoice_branding', app_types.JSONVariant(), nullable=False),
    sa.Column('org_id_override', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('org_path', sa.String(length=512), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['org_id_override'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_branding_configs_org_id'), 'branding_configs', ['org_id'], unique=False)
    op.create_index(op.f('ix_branding_configs_org_path'), 'branding_configs', ['org_path'], unique=False)
    op.create_table('commitments',
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('provider_code', sa.String(length=32), nullable=False),
    sa.Column('billing_account_id', sa.Uuid(), nullable=True),
    sa.Column('customer_id', sa.Uuid(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hourly_commitment', app_money.MoneyNumeric(), nullable=True),
    sa.Column('upfront_paid', app_money.MoneyNumeric(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('coverage_scope', app_types.JSONVariant(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('org_path', sa.String(length=512), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['billing_account_id'], ['cloud_billing_accounts.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commitments_billing_account_id'), 'commitments', ['billing_account_id'], unique=False)
    op.create_index(op.f('ix_commitments_customer_id'), 'commitments', ['customer_id'], unique=False)
    op.create_index(op.f('ix_commitments_org_id'), 'commitments', ['org_id'], unique=False)
    op.create_index(op.f('ix_commitments_org_path'), 'commitments', ['org_path'], unique=False)
    op.create_table('contracts',
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('org_path', sa.String(length=512), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contracts_customer_id'), 'contracts', ['customer_id'], unique=False)
    op.create_index(op.f('ix_contracts_org_id'), 'contracts', ['org_id'], unique=False)
    op.create_index(op.f('ix_contracts_org_path'), 'contracts', ['org_path'], unique=False)
    op.create_table('discount_programs',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('provider_code', sa.String(length=32), nullable=False),
    sa.Column('billing_account_id', sa.Uuid(), nullable=True),
    sa.Column('customer_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('rates', app_types.JSONVariant(), nullable=False),
    sa.Column('effective_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('org_path', sa.String(length=512), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['billing_account_id'], ['cloud_billing_accounts.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discount_programs_billing_account_id'), 'discount_programs', ['billing_account_id'], unique=False)
    op.create_index(op.f('ix_discount_programs_customer_id'), 'discount_programs', ['customer_id'], unique=False)
    op.create_index(op.f('ix_discount_programs_org_id'), 'discount_programs', ['org_id'], unique=False)
    op.create_index(op.f('ix_discount_programs_org_path'), 'discount_programs', ['org_path'], unique=False)
    op.create_table('finops_dimensions',
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('org_path', sa.String(length=512), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_path', 'kind', 'value', name='uq_dimension_value')
    )
    op.create_index(op.f('ix_finops_dimensions_customer_id'), 'finops_dimensions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_finops_dimensions_org_id'), 'finops_dimensions', ['org_id'], unique=False)
    op.create_index(op.f('ix_finops_dimensions_org_path'), 'finops_dimensions', ['org_path'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permission')
    )
    op.create_index(op.f('ix_role_permissions_role_id'), 'role_permissions', ['role_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('home_org_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('mfa_secret_encrypted', sa.Text(), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('agreed_terms_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['home_org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_home_org_id'), 'users', ['home_org_id'], unique=False)
    op.create_table('webhook_deliveries',
    sa.Column('endpoint_id', sa.Uuid(), nullable=False),
    sa.Column('org_path', sa.String(length=512), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', app_types.JSONVariant(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('response_code', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['webhook_endpoints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_deliveries_endpoint_id'), 'webhook_deliveries', ['endpoint_id'], unique=False)
    op.create_index(op.f('ix_webhook_deliveries_org_path'), 'webhook_deliveries', ['org_path'], unique=False)
    op.create_table('ai_query_audit',
    sa.Column('asked_by', sa.Uuid(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=64), nullable=True),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('tools_used', app_types.JSONVariant(), nullable=False),
    sa.Column('citations', app_types.JSONVariant(), nullable=False),
    sa.Column('exposed_customer_safe', sa.Boolean(), nullable=False),
    sa.Column('refused', sa.Boolean(), nullable=False),
    sa.Column('refusal_reason', sa.String(length=255), nullable=True),
    sa.Column('sensitive', sa.Boolean(), nullable=False),
    sa.Column('answer_summary', sa.String(length=512), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('org_path', sa.String(length=512), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['asked_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_query_audit_asked_by'), 'ai_query_audit', ['asked_by'], unique=False)
    op.create_index(op.f('ix_ai_query_audit_org_id'), 'ai_query_audit', ['org_id'], unique=False)
    op.create_index(op.f('ix_ai_query_audit_org_path'), 'ai_query_audit', ['org_path'], unique=False)
    op.create_table('api_tokens',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('scopes', app_types.JSONVariant(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_api_tokens_org_id'), 'api_tokens', ['org_id'], unique=False)
    op.create_table('approvals',
    sa.Column('request_number', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('impact_amount', app_money.MoneyNumeric(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('maker_id', sa.Uuid(), nullable=False),
    sa.Column('checker_id', sa.Uuid(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('context', app_types.JSONVariant(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('org_path', sa.String(length=512), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['checker_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['maker_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_number')
    )
    op.create_index(op.f('ix_approvals_entity_id'), 'approvals', ['entity_id'], unique=False)
    op.create_index(op.f('ix_approvals_org_id'), 'approvals', ['org_id'], unique=False)
    op.create_index(op.f('ix_approvals_org_path'), 'approvals', ['org_path'], unique=False)
    op.create_index(op.f('ix_approvals_status'), 'approvals', ['status'], unique=False)
    op.create_table('billing_rules',
    sa.Column('contract_id', sa.Uuid(), nullable=True),
    sa.Column('customer_id', sa.Uuid(), nullable=True),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('rule_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('org_path', sa.String(length=512), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_rules_contract_id'), 'billing_rules', ['contract_id'], unique=False)
    op.create_index(op.f('ix_billing_rules_customer_id'), 'billing_rules', ['customer_id'], unique=False)
    op.create_index(op.f('ix_billing_rules_org_id'), 'billing_rules', ['org_id'], unique=False)
    op.create_index(op.f('ix_billing_rules_org_path'), 'billing_rules', ['org_path'], unique=False)
    op.create_table('cloud_accounts',
    sa.Column('provider_code', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('billing_account_id', sa.Uuid(), nullable=True),
    sa.Column('account_family_id', sa.Uuid(), nullable=True),
    sa.Column('allocation_status', sa.String(length=32), nullable=False),
    sa.Column('mapped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('account_kind', sa.String(length=32), nullable=True),
    sa.Column('organization_path', sa.String(length=512), nullable=True),
    sa.Column('extra', app_types.JSONVariant(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('org_path', sa.String(length=512), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['account_family_id'], ['account_families.id'], ),
    sa.ForeignKeyConstraint(['billing_account_id'], ['cloud_billing_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_path', 'provider_code', 'external_id', name='uq_account_external')
    )
    op.create_index(op.f('ix_cloud_accounts_account_family_id'), 'cloud_accounts', ['account_family_id'], unique=False)
    op.create_index(op.f('ix_cloud_accounts_billing_account_id'), 'cloud_accounts', ['billing_account_id'], unique=False)
    op.create_index(op.f('ix_cloud_accounts_org_id'), 'cloud_accounts', ['org_id'], unique=False)
    op.create_index(op.f('ix_cloud_accounts_org_path'), 'cloud_accounts', ['org_path'], unique=False)
    op.create_table('contract_versions',
    sa.Column('contract_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('effective_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('billing_cadence', sa.String(length=32), nullable=False),
    sa.Column('payment_terms', sa.String(length=64), nullable=False),
    sa.Column('pricing_basis', sa.String(length=64), nullable=False),
    sa.Column('discount_policy', app_types.JSONVariant(), nullable=False),
    sa.Column('credit_sharing_policy', app_types.JSONVariant(), nullable=False),
    sa.Column('commitment_sharing_policy', app_types.JSONVariant(), nullable=False),
    sa.Column('support_fee_policy', app_types.JSONVariant(), nullable=False),
    sa.Column('tax_behavior', app_types.JSONVariant(), nullable=False),
    sa.Column('managed_service_fee', app_types.JSONVariant(), nullable=False),
    sa.Column('minimum_monthly', app_money.MoneyNumeric(), nullable=True),
    sa.Column('invoice_grouping', app_types.JSONVariant(), nullable=False),
    sa.Column('rounding_rule', app_types.JSONVariant(), nullable=False),
    sa.Column('approval_required', sa.Boolean(), nullable=False),
    sa.Column('custom_rates', app_types.JSONVariant(), nullable=False),
    sa.Column('rule_bindings', app_types.JSONVariant(), nullable=False),
    sa.Column('overlap_approved_by', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('org_path', sa.String(length=512), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_id', 'version_number', name='uq_contract_version')
    )
    op.create_index(op.f('ix_contract_versions_contract_id'), 'contract_versions', ['contract_id'], unique=False)
    op.create_index(op.f('ix_contract_versions_org_id'), 'contract_versions', ['org_id'], unique=False)
    op.create_index(op.f('ix_contract_versions_org_path'), 'contract_versions', ['org_path'], unique=False)
    op.create_table('export_jobs',
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('parameters', app_types.JSONVariant(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('requested_by', sa.Uuid(), nullable=True),
    sa.Column('object_key', sa.String(length=1024), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('correlation_id', sa.String(length=32), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('org_path', sa.String(length=512), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_export_jobs_org_id'), 'export_jobs', ['org_id'], unique=False)
    op.create_index(op.f('ix_export_jobs_org_path'), 'export_jobs', ['org_path'], unique=False)
    op.create_table('period_closes',
    sa.Column('billing_period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('billing_period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('closed_by', sa.Uuid(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reopen_reason', sa.Text(), nullable=True),
    sa.Column('summary', app_types.JSONVariant(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('org_path', sa.String(length=512), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['closed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_path', 'billing_period_start', name='uq_period_close')
    )
    op.create_index(op.f('ix_period_closes_org_id'), 'period_closes', ['org_id'], unique=False)
    op.create_index(op.f('ix_period_closes_org_path'), 'period_closes', ['org_path'], unique=False)
    op.create_table('raw_billing_files',
    sa.Column('org_path', sa.String(length=512), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('provider_code', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('object_key', sa.String(length=1024), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('billing_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('billing_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('parser_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('correlation_id', sa.String(length=32), nullable=True),
    sa.Column('ingested_by', sa.Uuid(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ingested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sha256', 'parser_version', name='uq_file_checksum_parser')
    )
    op.create_index(op.f('ix_raw_billing_files_org_id'), 'raw_billing_files', ['org_id'], unique=False)
    op.create_index(op.f('ix_raw_billing_files_org_path'), 'raw_billing_files', ['org_path'], unique=False)
    op.create_index(op.f('ix_raw_billing_files_status'), 'raw_billing_files', ['status'], unique=False)
    op.create_table('reconciliation_runs',
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('tolerance_abs', app_money.MoneyNumeric(), nullable=True),
    sa.Column('tolerance_pct', app_money.MoneyNumeric(), nullable=True),
    sa.Column('computed_by', sa.Uuid(), nullable=True),
    sa.Column('correlation_id', sa.String(length=32), nullable=True),
    sa.Column('summary', app_types.JSONVariant(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('org_path', sa.String(length=512), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['computed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_runs_org_id'), 'reconciliation_runs', ['org_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_runs_org_path'), 'reconciliation_runs', ['org_path'], unique=False)
    op.create_table('sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('csrf_token', sa.String(length=64), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_sessions_expires_at'), 'sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('user_role_assignments',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('attributes', app_types.JSONVariant(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', 'org_id', name='uq_user_role_org')
    )
    op.create_index(op.f('ix_user_role_assignments_org_id'), 'user_role_assignments', ['org_id'], unique=False)
    op.create_index(op.f('ix_user_role_assignments_role_id'), 'user_role_assignments', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_role_assignments_user_id'), 'user_role_assignments', ['user_id'], unique=False)
    op.create_table('billing_rule_versions',
    sa.Column('rule_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('calc_order', sa.Integer(), nullable=False),
    sa.Column('applied_basis', sa.String(length=64), nullable=False),
    sa.Column('filters', app_types.JSONVariant(), nullable=False),
    sa.Column('parameters', app_types.JSONVariant(), nullable=False),
    sa.Column('effective_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('high_impact', sa.Boolean(), nullable=False),
    sa.Column('estimated_impact_monthly', app_money.MoneyNumeric(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('org_path', sa.String(length=512), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['billing_rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id', 'version_number', name='uq_rule_version')
    )
    op.create_index(op.f('ix_billing_rule_versions_org_id'), 'billing_rule_versions', ['org_id'], unique=False)
    op.create_index(op.f('ix_billing_rule_versions_org_path'), 'billing_rule_versions', ['org_path'], unique=False)
    op.create_index(op.f('ix_billing_rule_versions_rule_id'), 'billing_rule_versions', ['rule_id'], unique=False)
    op.create_table('canonical_cost_records',
    sa.Column('lineage_file_id', sa.Uuid(), nullable=False),
    sa.Column('source_record_id', sa.String(length=255), nullable=False),
    sa.Column('org_path', sa.String(length=512), nullable=False),
    sa.Column('provider_code', sa.String(length=32), nullable=False),
    sa.Column('billing_period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('billing_period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('usage_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('usage_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('invoice_id', sa.String(length=128), nullable=True),
    sa.Column('payer_or_billing_account', sa.String(length=128), nullable=True),
    sa.Column('billing_account_id', sa.Uuid(), nullable=True),
    sa.Column('cloud_account_id', sa.Uuid(), nullable=True),
    sa.Column('account_family_id', sa.Uuid(), nullable=True),
    sa.Column('customer_id', sa.Uuid(), nullable=True),
    sa.Column('resource_id', sa.String(length=512), nullable=True),
    sa.Column('service', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=255), nullable=True),
    sa.Column('usage_type', sa.String(length=255), nullable=True),
    sa.Column('operation', sa.String(length=255), nullable=True),
    sa.Column('region', sa.String(length=128), nullable=True),
    sa.Column('availability_zone', sa.String(length=128), nullable=True),
    sa.Column('quantity', app_money.MoneyNumeric(), nullable=True),
    sa.Column('unit', sa.String(length=64), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('line_item_type', sa.String(length=64), nullable=False),
    sa.Column('cost_category', sa.String(length=64), nullable=True),
    sa.Column('list_cost', app_money.MoneyNumeric(), nullable=False),
    sa.Column('ondemand_equivalent', app_money.MoneyNumeric(), nullable=False),
    sa.Column('provider_billed', app_money.MoneyNumeric(), nullable=False),
    sa.Column('amortized', app_money.MoneyNumeric(), nullable=False),
    sa.Column('effective', app_money.MoneyNumeric(), nullable=False),
    sa.Column('net', app_money.MoneyNumeric(), nullable=False),
    sa.Column('credit', app_money.MoneyNumeric(), nullable=False),
    sa.Column('tax', app_money.MoneyNumeric(), nullable=False),
    sa.Column('support_fee', app_money.MoneyNumeric(), nullable=False),
    sa.Column('marketplace_fee', app_money.MoneyNumeric(), nullable=False),
    sa.Column('tags', app_types.JSONVariant(), nullable=False),
    sa.Column('application', sa.String(length=255), nullable=True),
    sa.Column('environment', sa.String(length=64), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('cost_center', sa.String(length=255), nullable=True),
    sa.Column('source_metadata', app_types.JSONVariant(), nullable=False),
    sa.Column('is_late_adjustment', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['account_family_id'], ['account_families.id'], ),
    sa.ForeignKeyConstraint(['billing_account_id'], ['cloud_billing_accounts.id'], ),
    sa.ForeignKeyConstraint(['cloud_account_id'], ['cloud_accounts.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['lineage_file_id'], ['raw_billing_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_record_id', 'lineage_file_id', name='uq_canonical_source_row')
    )
    op.create_index(op.f('ix_canonical_cost_records_cloud_account_id'), 'canonical_cost_records', ['cloud_account_id'], unique=False)
    op.create_index(op.f('ix_canonical_cost_records_customer_id'), 'canonical_cost_records', ['customer_id'], unique=False)
    op.create_index(op.f('ix_canonical_cost_records_lineage_file_id'), 'canonical_cost_records', ['lineage_file_id'], unique=False)
    op.create_index('ix_ccr_org_path_period', 'canonical_cost_records', ['org_path', 'billing_period_start'], unique=False)
    op.create_index('ix_ccr_period_account', 'canonical_cost_records', ['billing_period_start', 'cloud_account_id'], unique=False)
    op.create_index('ix_ccr_period_customer', 'canonical_cost_records', ['billing_period_start', 'customer_id'], unique=False)
    op.create_index('ix_ccr_service', 'canonical_cost_records', ['service'], unique=False)
    op.create_table('credits',
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('provider_code', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('billing_account_id', sa.Uuid(), nullable=True),
    sa.Column('customer_id', sa.Uuid(), nullable=True),
    sa.Column('amount_total', app_money.MoneyNumeric(), nullable=False),
    sa.Column('amount_used', app_money.MoneyNumeric(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('effective_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('allocation_status', sa.String(length=32), nullable=False),
    sa.Column('source_file_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('org_path', sa.String(length=512), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['billing_account_id'], ['cloud_billing_accounts.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['source_file_id'], ['raw_billing_files.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_path', 'provider_code', 'external_id', name='uq_credit_external')
    )
    op.create_index(op.f('ix_credits_allocation_status'), 'credits', ['allocation_status'], unique=False)
    op.create_index(op.f('ix_credits_billing_account_id'), 'credits', ['billing_account_id'], unique=False)
    op.create_index(op.f('ix_credits_customer_id'), 'credits', ['customer_id'], unique=False)
    op.create_index(op.f('ix_credits_org_id'), 'credits', ['org_id'], unique=False)
    op.create_index(op.f('ix_credits_org_path'), 'credits', ['org_path'], unique=False)
    op.create_table('pricing_runs',
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('contract_version_id', sa.Uuid(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('run_number', sa.Integer(), nullable=False),
    sa.Column('supersedes_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('engine_version', sa.String(length=32), nullable=False),
    sa.Column('triggered_by', sa.Uuid(), nullable=True),
    sa.Column('correlation_id', sa.String(length=32), nullable=True),
    sa.Column('input_summary', app_types.JSONVariant(), nullable=False),
    sa.Column('totals', app_types.JSONVariant(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approval_status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('org_path', sa.String(length=512), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['contract_version_id'], ['contract_versions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supersedes_id'], ['pricing_runs.id'], ),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_path', 'customer_id', 'period_start', 'run_number', name='uq_run_number')
    )
    op.create_index(op.f('ix_pricing_runs_customer_id'), 'pricing_runs', ['customer_id'], unique=False)
    op.create_index(op.f('ix_pricing_runs_org_id'), 'pricing_runs', ['org_id'], unique=False)
    op.create_index(op.f('ix_pricing_runs_org_path'), 'pricing_runs', ['org_path'], unique=False)
    op.create_index(op.f('ix_pricing_runs_status'), 'pricing_runs', ['status'], unique=False)
    op.create_table('quarantined_records',
    sa.Column('file_id', sa.Uuid(), nullable=True),
    sa.Column('org_path', sa.String(length=512), nullable=False),
    sa.Column('provider_code', sa.String(length=32), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('billing_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('payload', app_types.JSONVariant(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('resolved_by', sa.Uuid(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['raw_billing_files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_quarantine_status_period', 'quarantined_records', ['status', 'billing_period_start'], unique=False)
    op.create_index(op.f('ix_quarantined_records_file_id'), 'quarantined_records', ['file_id'], unique=False)
    op.create_index(op.f('ix_quarantined_records_org_path'), 'quarantined_records', ['org_path'], unique=False)
    op.create_index(op.f('ix_quarantined_records_status'), 'quarantined_records', ['status'], unique=False)
    op.create_table('raw_billing_records',
    sa.Column('file_id', sa.Uuid(), nullable=False),
    sa.Column('org_path', sa.String(length=512), nullable=False),
    sa.Column('provider_code', sa.String(length=32), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('source_record_id', sa.String(length=255), nullable=False),
    sa.Column('dedupe_key', sa.String(length=64), nullable=False),
    sa.Column('payload', app_types.JSONVariant(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['raw_billing_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id', 'row_number', name='uq_raw_row_position')
    )
    op.create_index(op.f('ix_raw_billing_records_file_id'), 'raw_billing_records', ['file_id'], unique=False)
    op.create_index(op.f('ix_raw_billing_records_org_path'), 'raw_billing_records', ['org_path'], unique=False)
    op.create_index('ix_raw_records_provider_key', 'raw_billing_records', ['provider_code', 'source_record_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('cloud_account_id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('org_path', sa.String(length=512), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['cloud_account_id'], ['cloud_accounts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_cloud_account_id'), 'subscriptions', ['cloud_account_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_org_id'), 'subscriptions', ['org_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_org_path'), 'subscriptions', ['org_path'], unique=False)
    op.create_table('invoices',
    sa.Column('invoice_number', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('account_family_id', sa.Uuid(), nullable=True),
    sa.Column('contract_version_id', sa.Uuid(), nullable=False),
    sa.Column('pricing_run_id', sa.Uuid(), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('grouping', app_types.JSONVariant(), nullable=False),
    sa.Column('subtotal', app_money.MoneyNumeric(), nullable=False),
    sa.Column('discounts_total', app_money.MoneyNumeric(), nullable=False),
    sa.Column('credits_total', app_money.MoneyNumeric(), nullable=False),
    sa.Column('fees_total', app_money.MoneyNumeric(), nullable=False),
    sa.Column('adjustments_total', app_money.MoneyNumeric(), nullable=False),
    sa.Column('taxes_total', app_money.MoneyNumeric(), nullable=False),
    sa.Column('prior_period_adjustments_total', app_money.MoneyNumeric(), nullable=False),
    sa.Column('total', app_money.MoneyNumeric(), nullable=False),
    sa.Column('provider_cost_total', app_money.MoneyNumeric(), nullable=False),
    sa.Column('margin_total', app_money.MoneyNumeric(), nullable=False),
    sa.Column('payment_terms', sa.String(length=64), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes_customer', sa.Text(), nullable=True),
    sa.Column('notes_internal', sa.Text(), nullable=True),
    sa.Column('branding_snapshot', app_types.JSONVariant(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('issued_by', sa.Uuid(), nullable=True),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('void_reason', sa.Text(), nullable=True),
    sa.Column('replaces_id', sa.Uuid(), nullable=True),
    sa.Column('exported_object_key', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('org_path', sa.String(length=512), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['account_family_id'], ['account_families.id'], ),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['contract_version_id'], ['contract_versions.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['issued_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pricing_run_id'], ['pricing_runs.id'], ),
    sa.ForeignKeyConstraint(['replaces_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_path', 'invoice_number', name='uq_invoice_number')
    )
    op.create_index(op.f('ix_invoices_customer_id'), 'invoices', ['customer_id'], unique=False)
    op.create_index(op.f('ix_invoices_org_id'), 'invoices', ['org_id'], unique=False)
    op.create_index(op.f('ix_invoices_org_path'), 'invoices', ['org_path'], unique=False)
    op.create_index(op.f('ix_invoices_pricing_run_id'), 'invoices', ['pricing_run_id'], unique=False)
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    op.create_table('pricing_run_items',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('org_path', sa.String(length=512), nullable=False),
    sa.Column('item_number', sa.Integer(), nullable=False),
    sa.Column('group_key', sa.String(length=512), nullable=False),
    sa.Column('group_label', sa.String(length=255), nullable=False),
    sa.Column('line_kind', sa.String(length=32), nullable=False),
    sa.Column('source_record_ids', app_types.JSONVariant(), nullable=False),
    sa.Column('rule_version_ids', app_types.JSONVariant(), nullable=False),
    sa.Column('input_amount', app_money.MoneyNumeric(), nullable=True),
    sa.Column('output_amount', app_money.MoneyNumeric(), nullable=False),
    sa.Column('provider_cost_amount', app_money.MoneyNumeric(), nullable=False),
    sa.Column('formula', sa.Text(), nullable=False),
    sa.Column('calculation_trace', app_types.JSONVariant(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('metadata', app_types.JSONVariant(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['pricing_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'item_number', name='uq_run_item_number')
    )
    op.create_index(op.f('ix_pricing_run_items_org_path'), 'pricing_run_items', ['org_path'], unique=False)
    op.create_index(op.f('ix_pricing_run_items_run_id'), 'pricing_run_items', ['run_id'], unique=False)
    op.create_table('pricing_run_rule_snapshots',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('org_path', sa.String(length=512), nullable=False),
    sa.Column('rule_id', sa.Uuid(), nullable=False),
    sa.Column('rule_version_id', sa.Uuid(), nullable=False),
    sa.Column('rule_code', sa.String(length=64), nullable=False),
    sa.Column('rule_type', sa.String(length=64), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('parameters', app_types.JSONVariant(), nullable=False),
    sa.Column('filters', app_types.JSONVariant(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('calc_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['pricing_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pricing_run_rule_snapshots_org_path'), 'pricing_run_rule_snapshots', ['org_path'], unique=False)
    op.create_index(op.f('ix_pricing_run_rule_snapshots_run_id'), 'pricing_run_rule_snapshots', ['run_id'], unique=False)
    op.create_table('resource_groups',
    sa.Column('subscription_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('org_path', sa.String(length=512), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_groups_org_id'), 'resource_groups', ['org_id'], unique=False)
    op.create_index(op.f('ix_resource_groups_org_path'), 'resource_groups', ['org_path'], unique=False)
    op.create_index(op.f('ix_resource_groups_subscription_id'), 'resource_groups', ['subscription_id'], unique=False)
    op.create_table('rule_sandbox_tests',
    sa.Column('rule_id', sa.Uuid(), nullable=False),
    sa.Column('rule_version_id', sa.Uuid(), nullable=False),
    sa.Column('tested_by', sa.Uuid(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('input_summary', app_types.JSONVariant(), nullable=False),
    sa.Column('result_summary', app_types.JSONVariant(), nullable=False),
    sa.Column('engine_version', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('org_path', sa.String(length=512), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['billing_rules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_version_id'], ['billing_rule_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_sandbox_tests_org_id'), 'rule_sandbox_tests', ['org_id'], unique=False)
    op.create_index(op.f('ix_rule_sandbox_tests_org_path'), 'rule_sandbox_tests', ['org_path'], unique=False)
    op.create_index(op.f('ix_rule_sandbox_tests_rule_id'), 'rule_sandbox_tests', ['rule_id'], unique=False)
    op.create_table('billing_notes',
    sa.Column('note_number', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('amount', app_money.MoneyNumeric(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('issued_by', sa.Uuid(), nullable=True),
    sa.Column('lines', app_types.JSONVariant(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('org_path', sa.String(length=512), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['issued_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_notes_customer_id'), 'billing_notes', ['customer_id'], unique=False)
    op.create_index(op.f('ix_billing_notes_invoice_id'), 'billing_notes', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_billing_notes_org_id'), 'billing_notes', ['org_id'], unique=False)
    op.create_index(op.f('ix_billing_notes_org_path'), 'billing_notes', ['org_path'], unique=False)
    op.create_table('disputes',
    sa.Column('dispute_number', sa.String(length=64), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=True),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('submitted_by', sa.Uuid(), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('amount_disputed', app_money.MoneyNumeric(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('org_path', sa.String(length=512), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disputes_customer_id'), 'disputes', ['customer_id'], unique=False)
    op.create_index(op.f('ix_disputes_invoice_id'), 'disputes', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_disputes_org_id'), 'disputes', ['org_id'], unique=False)
    op.create_index(op.f('ix_disputes_org_path'), 'disputes', ['org_path'], unique=False)
    op.create_index(op.f('ix_disputes_status'), 'disputes', ['status'], unique=False)
    op.create_table('invoice_lines',
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('org_path', sa.String(length=512), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('group_key', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('quantity', app_money.MoneyNumeric(), nullable=True),
    sa.Column('unit', sa.String(length=64), nullable=True),
    sa.Column('unit_rate', app_money.MoneyNumeric(), nullable=True),
    sa.Column('amount', app_money.MoneyNumeric(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('pricing_run_item_id', sa.Uuid(), nullable=True),
    sa.Column('source_record_ids', app_types.JSONVariant(), nullable=False),
    sa.Column('rule_version_ids', app_types.JSONVariant(), nullable=False),
    sa.Column('metadata', app_types.JSONVariant(), nullable=False),
    sa.Column('customer_visible', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pricing_run_item_id'], ['pricing_run_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_lines_invoice_id'), 'invoice_lines', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_invoice_lines_org_path'), 'invoice_lines', ['org_path'], unique=False)
    op.create_index(op.f('ix_invoice_lines_pricing_run_item_id'), 'invoice_lines', ['pricing_run_item_id'], unique=False)
    op.create_table('reconciliation_exceptions',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('dedupe_key', sa.String(length=255), nullable=False),
    sa.Column('exc_type', sa.String(length=64), nullable=False),
    sa.Column('materiality', sa.String(length=16), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=True),
    sa.Column('billing_account_ref', sa.String(length=128), nullable=True),
    sa.Column('invoice_id', sa.Uuid(), nullable=True),
    sa.Column('amount_delta', app_money.MoneyNumeric(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('evidence', app_types.JSONVariant(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('owner_user_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('waived_by', sa.Uuid(), nullable=True),
    sa.Column('waiver_approval_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('org_path', sa.String(length=512), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['reconciliation_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['waived_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['waiver_approval_id'], ['approvals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'dedupe_key', name='uq_exception_key')
    )
    op.create_index(op.f('ix_reconciliation_exceptions_customer_id'), 'reconciliation_exceptions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_exceptions_exc_type'), 'reconciliation_exceptions', ['exc_type'], unique=False)
    op.create_index(op.f('ix_reconciliation_exceptions_org_id'), 'reconciliation_exceptions', ['org_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_exceptions_org_path'), 'reconciliation_exceptions', ['org_path'], unique=False)
    op.create_index(op.f('ix_reconciliation_exceptions_run_id'), 'reconciliation_exceptions', ['run_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_exceptions_status'), 'reconciliation_exceptions', ['status'], unique=False)
    if op.get_bind().dialect.name == "postgresql":
        _apply_tenant_rls_and_integrity()
    # ### end Alembic commands ###


def _apply_tenant_rls_and_integrity() -> None:
    """PostgreSQL-only: row-level security per tenant subtree + append-only
    audit + issued-invoice immutability. The application role (non-owner,
    NOBYPASSRLS) is always subject to these policies; the schema-owner
    (migration) role bypasses them by design.

    Scope contract: `app.current_org_path` must be set per transaction by the
    API layer; unset or the '@@deny@@' sentinel => deny-all."""

    scoped_tables = [
        "customers", "account_families", "cloud_billing_accounts", "cloud_accounts",
        "subscriptions", "resource_groups", "finops_dimensions",
        "raw_billing_files", "raw_billing_records", "quarantined_records",
        "canonical_cost_records",
        "contracts", "contract_versions", "billing_rules", "billing_rule_versions",
        "rule_sandbox_tests",
        "commitments", "credits", "discount_programs", "allocation_policies",
        "pricing_runs", "pricing_run_items", "pricing_run_rule_snapshots",
        "invoices", "invoice_lines", "invoice_sequences", "billing_notes", "disputes",
        "export_jobs", "period_closes",
        "provider_bill_totals", "reconciliation_runs", "reconciliation_exceptions",
        "approvals", "integrations", "webhook_endpoints", "webhook_deliveries",
        "notification_outbox",
        "branding_configs", "ai_query_audit", "audit_events",
    ]

    for t in scoped_tables:
        op.execute(f'ALTER TABLE "{t}" ENABLE ROW LEVEL SECURITY')
        op.execute(
            f"""
            CREATE POLICY tenant_scope ON "{t}"
              USING (
                left(org_path, length(current_setting('app.current_org_path', true)))
                = current_setting('app.current_org_path', true)
              )
              WITH CHECK (
                left(org_path, length(current_setting('app.current_org_path', true)))
                = current_setting('app.current_org_path', true)
              )
            """)

    op.execute("REVOKE UPDATE, DELETE ON audit_events FROM partnerops")
    op.execute("""
        CREATE OR REPLACE FUNCTION audit_events_no_mutate() RETURNS trigger AS $$
        BEGIN
          IF COALESCE(current_setting('app.audit_maintenance', true), '') = 'on' THEN
            IF (TG_OP = 'DELETE') THEN
              RETURN OLD;
            ELSE
              RETURN NEW;
            END IF;
          END IF;
          RAISE EXCEPTION 'audit_events is append-only';
        END $$ LANGUAGE plpgsql
    """)
    op.execute("""
        CREATE TRIGGER audit_events_append_only
          BEFORE UPDATE OR DELETE ON audit_events
          FOR EACH ROW EXECUTE FUNCTION audit_events_no_mutate()
    """)

    op.execute("ALTER TABLE organizations ENABLE ROW LEVEL SECURITY")
    op.execute("""
        CREATE POLICY org_subtree ON organizations
          USING (
            left(path, length(current_setting('app.current_org_path', true)))
            = current_setting('app.current_org_path', true)
          )
          WITH CHECK (
            left(path, length(current_setting('app.current_org_path', true)))
            = current_setting('app.current_org_path', true)
          )
    """)

    op.execute("""
        CREATE OR REPLACE FUNCTION invoice_immutable_guard() RETURNS trigger AS $$
        BEGIN
          IF OLD.status = 'issued' AND NEW.status IS DISTINCT FROM OLD.status
             AND NEW.status NOT IN ('exported', 'paid_or_settled', 'disputed', 'corrected', 'voided') THEN
            RAISE EXCEPTION 'issued invoice cannot transition out of issued state';
          END IF;
          IF OLD.status IN ('issued', 'exported', 'corrected', 'voided')
             AND (NEW.total IS DISTINCT FROM OLD.total
                  OR NEW.subtotal IS DISTINCT FROM OLD.subtotal
                  OR NEW.invoice_number IS DISTINCT FROM OLD.invoice_number
                  OR NEW.period_start IS DISTINCT FROM OLD.period_start) THEN
            RAISE EXCEPTION 'issued invoice financial fields are immutable';
          END IF;
          RETURN NEW;
        END $$ LANGUAGE plpgsql
    """)
    op.execute("""
        CREATE TRIGGER invoices_immutable BEFORE UPDATE ON invoices
          FOR EACH ROW EXECUTE FUNCTION invoice_immutable_guard()
    """)
    op.execute("""
        CREATE OR REPLACE FUNCTION invoice_lines_immutable_guard() RETURNS trigger AS $$
        DECLARE inv_status text;
        BEGIN
          SELECT status INTO inv_status FROM invoices WHERE id = OLD.invoice_id;
          IF inv_status IN ('issued', 'exported') THEN
            RAISE EXCEPTION 'invoice lines are immutable once issued';
          END IF;
          RETURN NEW;
        END $$ LANGUAGE plpgsql
    """)
    op.execute("""
        CREATE TRIGGER invoice_lines_immutable BEFORE UPDATE OR DELETE ON invoice_lines
          FOR EACH ROW EXECUTE FUNCTION invoice_lines_immutable_guard()
    """)



def downgrade() -> None:
    if op.get_bind().dialect.name == "postgresql":
        op.execute("DROP TRIGGER IF EXISTS invoice_lines_immutable ON invoice_lines")
        op.execute("DROP TRIGGER IF EXISTS invoices_immutable ON invoices")
        op.execute("DROP TRIGGER IF EXISTS audit_events_append_only ON audit_events")
        op.execute("DROP FUNCTION IF EXISTS invoice_immutable_guard()")
        op.execute("DROP FUNCTION IF EXISTS invoice_lines_immutable_guard()")
        op.execute("DROP FUNCTION IF EXISTS audit_events_no_mutate()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reconciliation_exceptions_status'), table_name='reconciliation_exceptions')
    op.drop_index(op.f('ix_reconciliation_exceptions_run_id'), table_name='reconciliation_exceptions')
    op.drop_index(op.f('ix_reconciliation_exceptions_org_path'), table_name='reconciliation_exceptions')
    op.drop_index(op.f('ix_reconciliation_exceptions_org_id'), table_name='reconciliation_exceptions')
    op.drop_index(op.f('ix_reconciliation_exceptions_exc_type'), table_name='reconciliation_exceptions')
    op.drop_index(op.f('ix_reconciliation_exceptions_customer_id'), table_name='reconciliation_exceptions')
    op.drop_table('reconciliation_exceptions')
    op.drop_index(op.f('ix_invoice_lines_pricing_run_item_id'), table_name='invoice_lines')
    op.drop_index(op.f('ix_invoice_lines_org_path'), table_name='invoice_lines')
    op.drop_index(op.f('ix_invoice_lines_invoice_id'), table_name='invoice_lines')
    op.drop_table('invoice_lines')
    op.drop_index(op.f('ix_disputes_status'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_org_path'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_org_id'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_invoice_id'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_customer_id'), table_name='disputes')
    op.drop_table('disputes')
    op.drop_index(op.f('ix_billing_notes_org_path'), table_name='billing_notes')
    op.drop_index(op.f('ix_billing_notes_org_id'), table_name='billing_notes')
    op.drop_index(op.f('ix_billing_notes_invoice_id'), table_name='billing_notes')
    op.drop_index(op.f('ix_billing_notes_customer_id'), table_name='billing_notes')
    op.drop_table('billing_notes')
    op.drop_index(op.f('ix_rule_sandbox_tests_rule_id'), table_name='rule_sandbox_tests')
    op.drop_index(op.f('ix_rule_sandbox_tests_org_path'), table_name='rule_sandbox_tests')
    op.drop_index(op.f('ix_rule_sandbox_tests_org_id'), table_name='rule_sandbox_tests')
    op.drop_table('rule_sandbox_tests')
    op.drop_index(op.f('ix_resource_groups_subscription_id'), table_name='resource_groups')
    op.drop_index(op.f('ix_resource_groups_org_path'), table_name='resource_groups')
    op.drop_index(op.f('ix_resource_groups_org_id'), table_name='resource_groups')
    op.drop_table('resource_groups')
    op.drop_index(op.f('ix_pricing_run_rule_snapshots_run_id'), table_name='pricing_run_rule_snapshots')
    op.drop_index(op.f('ix_pricing_run_rule_snapshots_org_path'), table_name='pricing_run_rule_snapshots')
    op.drop_table('pricing_run_rule_snapshots')
    op.drop_index(op.f('ix_pricing_run_items_run_id'), table_name='pricing_run_items')
    op.drop_index(op.f('ix_pricing_run_items_org_path'), table_name='pricing_run_items')
    op.drop_table('pricing_run_items')
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_pricing_run_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_org_path'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_org_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_customer_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_subscriptions_org_path'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_org_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_cloud_account_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index('ix_raw_records_provider_key', table_name='raw_billing_records')
    op.drop_index(op.f('ix_raw_billing_records_org_path'), table_name='raw_billing_records')
    op.drop_index(op.f('ix_raw_billing_records_file_id'), table_name='raw_billing_records')
    op.drop_table('raw_billing_records')
    op.drop_index(op.f('ix_quarantined_records_status'), table_name='quarantined_records')
    op.drop_index(op.f('ix_quarantined_records_org_path'), table_name='quarantined_records')
    op.drop_index(op.f('ix_quarantined_records_file_id'), table_name='quarantined_records')
    op.drop_index('ix_quarantine_status_period', table_name='quarantined_records')
    op.drop_table('quarantined_records')
    op.drop_index(op.f('ix_pricing_runs_status'), table_name='pricing_runs')
    op.drop_index(op.f('ix_pricing_runs_org_path'), table_name='pricing_runs')
    op.drop_index(op.f('ix_pricing_runs_org_id'), table_name='pricing_runs')
    op.drop_index(op.f('ix_pricing_runs_customer_id'), table_name='pricing_runs')
    op.drop_table('pricing_runs')
    op.drop_index(op.f('ix_credits_org_path'), table_name='credits')
    op.drop_index(op.f('ix_credits_org_id'), table_name='credits')
    op.drop_index(op.f('ix_credits_customer_id'), table_name='credits')
    op.drop_index(op.f('ix_credits_billing_account_id'), table_name='credits')
    op.drop_index(op.f('ix_credits_allocation_status'), table_name='credits')
    op.drop_table('credits')
    op.drop_index('ix_ccr_service', table_name='canonical_cost_records')
    op.drop_index('ix_ccr_period_customer', table_name='canonical_cost_records')
    op.drop_index('ix_ccr_period_account', table_name='canonical_cost_records')
    op.drop_index('ix_ccr_org_path_period', table_name='canonical_cost_records')
    op.drop_index(op.f('ix_canonical_cost_records_lineage_file_id'), table_name='canonical_cost_records')
    op.drop_index(op.f('ix_canonical_cost_records_customer_id'), table_name='canonical_cost_records')
    op.drop_index(op.f('ix_canonical_cost_records_cloud_account_id'), table_name='canonical_cost_records')
    op.drop_table('canonical_cost_records')
    op.drop_index(op.f('ix_billing_rule_versions_rule_id'), table_name='billing_rule_versions')
    op.drop_index(op.f('ix_billing_rule_versions_org_path'), table_name='billing_rule_versions')
    op.drop_index(op.f('ix_billing_rule_versions_org_id'), table_name='billing_rule_versions')
    op.drop_table('billing_rule_versions')
    op.drop_index(op.f('ix_user_role_assignments_user_id'), table_name='user_role_assignments')
    op.drop_index(op.f('ix_user_role_assignments_role_id'), table_name='user_role_assignments')
    op.drop_index(op.f('ix_user_role_assignments_org_id'), table_name='user_role_assignments')
    op.drop_table('user_role_assignments')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_expires_at'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_reconciliation_runs_org_path'), table_name='reconciliation_runs')
    op.drop_index(op.f('ix_reconciliation_runs_org_id'), table_name='reconciliation_runs')
    op.drop_table('reconciliation_runs')
    op.drop_index(op.f('ix_raw_billing_files_status'), table_name='raw_billing_files')
    op.drop_index(op.f('ix_raw_billing_files_org_path'), table_name='raw_billing_files')
    op.drop_index(op.f('ix_raw_billing_files_org_id'), table_name='raw_billing_files')
    op.drop_table('raw_billing_files')
    op.drop_index(op.f('ix_period_closes_org_path'), table_name='period_closes')
    op.drop_index(op.f('ix_period_closes_org_id'), table_name='period_closes')
    op.drop_table('period_closes')
    op.drop_index(op.f('ix_export_jobs_org_path'), table_name='export_jobs')
    op.drop_index(op.f('ix_export_jobs_org_id'), table_name='export_jobs')
    op.drop_table('export_jobs')
    op.drop_index(op.f('ix_contract_versions_org_path'), table_name='contract_versions')
    op.drop_index(op.f('ix_contract_versions_org_id'), table_name='contract_versions')
    op.drop_index(op.f('ix_contract_versions_contract_id'), table_name='contract_versions')
    op.drop_table('contract_versions')
    op.drop_index(op.f('ix_cloud_accounts_org_path'), table_name='cloud_accounts')
    op.drop_index(op.f('ix_cloud_accounts_org_id'), table_name='cloud_accounts')
    op.drop_index(op.f('ix_cloud_accounts_billing_account_id'), table_name='cloud_accounts')
    op.drop_index(op.f('ix_cloud_accounts_account_family_id'), table_name='cloud_accounts')
    op.drop_table('cloud_accounts')
    op.drop_index(op.f('ix_billing_rules_org_path'), table_name='billing_rules')
    op.drop_index(op.f('ix_billing_rules_org_id'), table_name='billing_rules')
    op.drop_index(op.f('ix_billing_rules_customer_id'), table_name='billing_rules')
    op.drop_index(op.f('ix_billing_rules_contract_id'), table_name='billing_rules')
    op.drop_table('billing_rules')
    op.drop_index(op.f('ix_approvals_status'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_org_path'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_org_id'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_entity_id'), table_name='approvals')
    op.drop_table('approvals')
    op.drop_index(op.f('ix_api_tokens_org_id'), table_name='api_tokens')
    op.drop_table('api_tokens')
    op.drop_index(op.f('ix_ai_query_audit_org_path'), table_name='ai_query_audit')
    op.drop_index(op.f('ix_ai_query_audit_org_id'), table_name='ai_query_audit')
    op.drop_index(op.f('ix_ai_query_audit_asked_by'), table_name='ai_query_audit')
    op.drop_table('ai_query_audit')
    op.drop_index(op.f('ix_webhook_deliveries_endpoint_id'), table_name='webhook_deliveries')
    op.drop_table('webhook_deliveries')
    op.drop_index(op.f('ix_users_home_org_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_role_permissions_role_id'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_finops_dimensions_org_path'), table_name='finops_dimensions')
    op.drop_index(op.f('ix_finops_dimensions_org_id'), table_name='finops_dimensions')
    op.drop_index(op.f('ix_finops_dimensions_customer_id'), table_name='finops_dimensions')
    op.drop_table('finops_dimensions')
    op.drop_index(op.f('ix_discount_programs_org_path'), table_name='discount_programs')
    op.drop_index(op.f('ix_discount_programs_org_id'), table_name='discount_programs')
    op.drop_index(op.f('ix_discount_programs_customer_id'), table_name='discount_programs')
    op.drop_index(op.f('ix_discount_programs_billing_account_id'), table_name='discount_programs')
    op.drop_table('discount_programs')
    op.drop_index(op.f('ix_contracts_org_path'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_org_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_customer_id'), table_name='contracts')
    op.drop_table('contracts')
    op.drop_index(op.f('ix_commitments_org_path'), table_name='commitments')
    op.drop_index(op.f('ix_commitments_org_id'), table_name='commitments')
    op.drop_index(op.f('ix_commitments_customer_id'), table_name='commitments')
    op.drop_index(op.f('ix_commitments_billing_account_id'), table_name='commitments')
    op.drop_table('commitments')
    op.drop_index(op.f('ix_branding_configs_org_path'), table_name='branding_configs')
    op.drop_index(op.f('ix_branding_configs_org_id'), table_name='branding_configs')
    op.drop_table('branding_configs')
    op.drop_index(op.f('ix_account_families_org_path'), table_name='account_families')
    op.drop_index(op.f('ix_account_families_org_id'), table_name='account_families')
    op.drop_index(op.f('ix_account_families_customer_id'), table_name='account_families')
    op.drop_table('account_families')
    op.drop_index(op.f('ix_webhook_endpoints_org_path'), table_name='webhook_endpoints')
    op.drop_index(op.f('ix_webhook_endpoints_org_id'), table_name='webhook_endpoints')
    op.drop_table('webhook_endpoints')
    op.drop_table('roles')
    op.drop_table('provider_bill_totals')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_organizations_parent_id'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_notification_outbox_org_path'), table_name='notification_outbox')
    op.drop_index(op.f('ix_notification_outbox_org_id'), table_name='notification_outbox')
    op.drop_table('notification_outbox')
    op.drop_table('invoice_sequences')
    op.drop_index(op.f('ix_integrations_org_path'), table_name='integrations')
    op.drop_index(op.f('ix_integrations_org_id'), table_name='integrations')
    op.drop_table('integrations')
    op.drop_index(op.f('ix_customers_org_path'), table_name='customers')
    op.drop_index(op.f('ix_customers_org_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_table('cloud_providers')
    op.drop_index(op.f('ix_cloud_billing_accounts_org_path'), table_name='cloud_billing_accounts')
    op.drop_index(op.f('ix_cloud_billing_accounts_org_id'), table_name='cloud_billing_accounts')
    op.drop_table('cloud_billing_accounts')
    op.drop_index(op.f('ix_audit_events_org_path'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_correlation_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor_user_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_allocation_policies_org_path'), table_name='allocation_policies')
    op.drop_index(op.f('ix_allocation_policies_org_id'), table_name='allocation_policies')
    op.drop_table('allocation_policies')
    # ### end Alembic commands ###
